import sys, os
import ast

import pathlib2


CLASSES_WITH_OBSOLETE_MEMBERS = {
	"QAbstractItemModel" : ["setSupportedDragActions","reset","setRoleNames"],
	"QAbstractItemView" : ["horizontalStepsPerItem","setHorizontalStepsPerItem","setVerticalStepsPerItem","verticalStepsPerItem"],
	"QApplication" : ["ColorSpec","colorSpec","keyboardInputDirection","keyboardInputLocale","keypadNavigationEnabled","setColorSpec","setGraphicsSystem","setKeypadNavigationEnabled"],
	"QColor" : ["dark","light"],
	"QColorDialog" : ["getRgba"],
	"QComboBox" : ["autoCompletion","autoCompletionCaseSensitivity"],
	"QCoreApplication" : ["Encoding","flush","hasPendingEvents","translate"],
	"QDialog" : ["extension","orientation","setExtension","setOrientation","showExtension"],
	"QDrag" : ["start"],
	"QFile" : ["EncoderFn","readLink","readLink","setDecodingFunction","setEncodingFunction"],
	"QFileDialog" : ["confirmOverwrite","nameFilterDetailsVisible","readOnly","resolveSymlinks"],
	"QFont" : ["rawMode","rawName","setRawMode","setRawName","removeSubstitution"],
	"QFontDatabase" : ["supportsThreadedFontRendering"],
	"QHeaderView" : ["isClickable","isMovable","resizeMode","setClickable","setMovable","setResizeMode","setResizeMode"],
	"QIcon" : ["serialNumber"],
	"QImage" : ["alphaChannel","byteCount","numBytes","numColors","serialNumber","setAlphaChannel","setNumColors","setText","text","text","textLanguages","textList"],
	"QInputDialog" : ["getInteger"],
	"QLayout" : ["margin"],
	"QListWidget" : ["isItemHidden","isItemSelected","setItemHidden","setItemSelected"],
	"QListWidgetItem" : ["backgroundColor","setBackgroundColor","setTextColor","textColor"],
	"QMessageBox" : ["Button","QMessageBox","buttonText","setButtonText","critical","critical","information","information","question","question","standardIcon","warning","warning"],
	"QModelIndex" : ["child"],
	"QMouseEvent" : ["posF"],
	"QObject" : ["dumpObjectInfo","dumpObjectTree","trUtf8","qFindChild","qFindChildren","Q_ENUMS","Q_FLAGS"],
	"QPainter" : ["combinedMatrix","deviceMatrix","drawRoundRect","drawRoundRect","drawRoundRect","initFrom","matrix","matrixEnabled","resetMatrix","setMatrix","setMatrixEnabled","setWorldMatrix","worldMatrix","redirected","restoreRedirected","setRedirected"],
	"QPalette" : ["QPalette","background","foreground","serialNumber"],
	"QPixmap" : ["fill","fill","serialNumber","grabWidget","grabWidget","grabWindow"],
	"QProcess" : ["environment","pid","readChannelMode","setEnvironment","setReadChannelMode","error","finished"],
	"QStyle" : ["standardPixmap"],
	"QTableView" : ["sortByColumn"],
	"QTableWidget" : ["isItemSelected","setItemSelected"],
	"QTableWidgetItem" : ["backgroundColor","setBackgroundColor","setTextColor","textColor"],
	"QTextEdit" : ["tabStopWidth"],
	"QTextOption" : ["setTabStop","tabStop"],
	"QTreeView" : ["sortByColumn"],
	"QTreeWidget" : ["isItemExpanded","isItemHidden","isItemSelected","setItemExpanded","setItemHidden","setItemSelected","items"],
	"QTreeWidgetItem" : ["backgroundColor","setBackgroundColor","setTextColor","textColor"],
	"QUrl" : ["addEncodedQueryItem","addQueryItem","allEncodedQueryItemValues","allQueryItemValues","encodedFragment","encodedHost","encodedPassword","encodedPath","encodedQuery","encodedQueryItemValue","encodedQueryItems","encodedUserName","hasEncodedQueryItem","hasQueryItem","queryItemValue","queryItems","removeAllEncodedQueryItems","removeAllQueryItems","removeEncodedQueryItem","removeQueryItem","setEncodedFragment","setEncodedHost","setEncodedPassword","setEncodedPath","setEncodedQuery","setEncodedQueryItems","setEncodedUrl","setEncodedUserName","setQueryItems","fromPunycode","toPunycode"],
	"QVariant" : ["Type","qVariantCanConvert","qVariantFromValue","qVariantSetValue","qVariantValue"],
	"QWheelEvent" : ["QWheelEvent","QWheelEvent","delta","orientation"],
	"QWidget" : ["windowIconText","isEnabledToTLW","isTopLevel","topLevelWidget"],
}

CLASSES_IN_QtWidgets = [
	"QAbstractButton",
	"QGraphicsAnchor",
	"QMacCocoaViewContainer",
	"QStyleOptionGroupBox",
	"QAbstractGraphicsShapeItem",
	"QGraphicsAnchorLayout",
	"QMainWindow",
	"QStyleOptionHeader",
	"QAbstractItemDelegate",
	"QGraphicsBlurEffect",
	"QMdiArea",
	"QStyleOptionMenuItem",
	"QAbstractItemView",
	"QGraphicsColorizeEffect",
	"QMdiSubWindow",
	"QStyleOptionProgressBar",
	"QAbstractScrollArea",
	"QGraphicsDropShadowEffect",
	"QMenu",
	"QStyleOptionRubberBand",
	"QAbstractSlider",
	"QGraphicsEffect",
	"QMenuBar",
	"QStyleOptionSizeGrip",
	"QAbstractSpinBox",
	"QGraphicsEllipseItem",
	"QMessageBox",
	"QStyleOptionSlider",
	"QAction",
	"QGraphicsGridLayout",
	"QMouseEventTransition",
	"QStyleOptionSpinBox",
	"QActionGroup",
	"QGraphicsItem",
	"QOpenGLWidget",
	"QStyleOptionTab",
	"QApplication",
	"GraphicsItemFlags",
	"OptimizationFlags",
	"QStyleOptionTabBarBase",
	"AreaOptions",
	"QGraphicsItemGroup",
	"Options",
	"QStyleOptionTabWidgetFrame",
	"AutoFormatting",
	"QGraphicsLayout",
	"Options",
	"QStyleOptionTitleBar",
	"BlurHints",
	"QGraphicsLayoutItem",
	"QPanGesture",
	"QStyleOptionToolBar",
	"QBoxLayout",
	"QGraphicsLineItem",
	"QPinchGesture",
	"QStyleOptionToolBox",
	"ButtonFeatures",
	"QGraphicsLinearLayout",
	"QPlainTextDocumentLayout",
	"QStyleOptionToolButton",
	"QButtonGroup",
	"QGraphicsObject",
	"QPlainTextEdit",
	"QStyleOptionViewItem",
	"CacheMode",
	"QGraphicsOpacityEffect",
	"QProgressBar",
	"QStylePainter",
	"QCalendarWidget",
	"QGraphicsPathItem",
	"QProgressDialog",
	"QStyledItemDelegate",
	"ChangeFlags",
	"QGraphicsPixmapItem",
	"QProxyStyle",
	"SubControls",
	"ChangeFlags",
	"QGraphicsPolygonItem",
	"QPushButton",
	"SubWindowOptions",
	"QCheckBox",
	"QGraphicsProxyWidget",
	"QRadioButton",
	"QSwipeGesture",
	"QColorDialog",
	"QGraphicsRectItem",
	"RenderFlags",
	"QSystemTrayIcon",
	"ColorDialogOptions",
	"QGraphicsRotation",
	"Result",
	"QTabBar",
	"QColumnView",
	"QGraphicsScale",
	"QRubberBand",
	"TabFeatures",
	"QComboBox",
	"QGraphicsScene",
	"SceneLayers",
	"QTabWidget",
	"QCommandLinkButton",
	"QGraphicsSceneContextMenuEvent",
	"QScrollArea",
	"QTableView",
	"QCommonStyle",
	"QGraphicsSceneDragDropEvent",
	"QScrollBar",
	"QTableWidget",
	"QCompleter",
	"QGraphicsSceneEvent",
	"QScroller",
	"QTableWidgetItem",
	"ControlTypes",
	"QGraphicsSceneHelpEvent",
	"QScrollerProperties",
	"QTableWidgetSelectionRange",
	"CornerWidgets",
	"QGraphicsSceneHoverEvent",
	"Sections",
	"TakeRowResult",
	"QDataWidgetMapper",
	"QGraphicsSceneMouseEvent",
	"QShortcut",
	"QTapAndHoldGesture",
	"QDateEdit",
	"QGraphicsSceneMoveEvent",
	"QSizeGrip",
	"QTapGesture",
	"QDateTimeEdit",
	"QGraphicsSceneResizeEvent",
	"QSizePolicy",
	"QTextBrowser",
	"QDesktopWidget",
	"QGraphicsSceneWheelEvent",
	"QSlider",
	"QTextEdit",
	"QDial",
	"QGraphicsSimpleTextItem",
	"QSpacerItem",
	"QTimeEdit",
	"QDialog",
	"QGraphicsTextItem",
	"QSpinBox",
	"QToolBar",
	"QDialogButtonBox",
	"QGraphicsTransform",
	"QSplashScreen",
	"ToolBarFeatures",
	"QDirModel",
	"QGraphicsView",
	"QSplitter",
	"QToolBox",
	"DockOptions",
	"QGraphicsWidget",
	"QSplitterHandle",
	"QToolButton",
	"QDockWidget",
	"QGridLayout",
	"QStackedLayout",
	"ToolButtonFeatures",
	"DockWidgetFeatures",
	"QGroupBox",
	"QStackedWidget",
	"QToolTip",
	"QDoubleSpinBox",
	"QHBoxLayout",
	"StandardButtons",
	"QTreeView",
	"EditTriggers",
	"QHeaderView",
	"StandardButtons",
	"QTreeWidget",
	"QErrorMessage",
	"QInputDialog",
	"State",
	"QTreeWidgetItem",
	"ExtraSelection",
	"InputDialogOptions",
	"QStatusBar",
	"QTreeWidgetItemIterator",
	"QFileDialog",
	"QItemDelegate",
	"StepEnabled",
	"QUndoCommand",
	"QFileIconProvider",
	"QItemEditorCreatorBase",
	"QStyle",
	"QUndoGroup",
	"QFileSystemModel",
	"QItemEditorFactory",
	"QStyleFactory",
	"QUndoStack",
	"QFocusFrame",
	"IteratorFlags",
	"QStyleHintReturn",
	"QUndoView",
	"QFontComboBox",
	"QKeyEventTransition",
	"QStyleHintReturnMask",
	"QVBoxLayout",
	"QFontDialog",
	"QKeySequenceEdit",
	"QStyleHintReturnVariant",
	"ViewItemFeatures",
	"FontDialogOptions",
	"QLCDNumber",
	"QStyleOption",
	"QWhatsThis",
	"FontFilters",
	"QLabel",
	"QStyleOptionButton",
	"QWidget",
	"QFormLayout",
	"QLayout",
	"QStyleOptionComboBox",
	"QWidgetAction",
	"QFrame",
	"QLayoutItem",
	"QStyleOptionComplex",
	"QWidgetItem",
	"FrameFeatures",
	"QLineEdit",
	"QStyleOptionDockWidget",
	"QWizard",
	"QGesture",
	"QListView",
	"QStyleOptionFocusRect",
	"WizardOptions",
	"QGestureEvent",
	"QListWidget",
	"QStyleOptionFrame",
	"QWizardPage",
	"QGestureRecognizer",
	"QListWidgetItem",
	"QStyleOptionGraphicsItem",
]

classes = CLASSES_WITH_OBSOLETE_MEMBERS.keys()
functions = {}

for k in CLASSES_WITH_OBSOLETE_MEMBERS:
	for i in CLASSES_WITH_OBSOLETE_MEMBERS[k]:
		functions[i] = 0

# print(functions)
# sys.exit(0)
cur = pathlib2.Path('.')

search_space = ["QtGui." + i for i in CLASSES_IN_QtWidgets]
for p in (p for p in cur.glob('**/*.py') if \
		  not str(p).startswith('sparx') \
		  and p.parent != pathlib2.Path(__file__).parent):
	with p.open() as fin:
		lines = fin.readlines()
	
	for s in CLASSES_IN_QtWidgets:
		for i in range(len(lines)):
			if "QtGui." + s in lines[i]:
				print("QtGui.{0} -> QtWidgets.{0}".format(s))
				lines[i] = lines[i].replace("QtGui." + s, "QtWidgets."  + s)
			# print("{}: {}".format(s,p))
	
	print("Writing: {} ....".format(p))
	with p.open(mode='w') as fout:
		fout.writelines(lines)
